### ISSUE TITLE
an error

### ISSUE THREAD

**Issue by Jee20** [doadin/PlexusIndicatorsDynamic#1]
getting an error, cannot see options inside Plexus

`1x PlexusIndicatorsDynamic\Options-Options.lua:384: attempt to index field '?' (a nil value)
[string "@PlexusIndicatorsDynamic\Options-Options.lua"]:384: in function `Reset'
[string "@PlexusIndicatorsDynamic\Options-Options.lua"]:396: in function <PlexusIndicatorsDynamic\Options.lua:392>
[string "=[C]"]: ?
[string "@ArkInventory\Externals\Ace3\AceAddon\AceAddon-3.0-13.lua"]:70: in function <...rkInventory\Externals\Ace3\AceAddon\AceAddon-3.0.lua:65>
[string "@ArkInventory\Externals\Ace3\AceAddon\AceAddon-3.0-13.lua"]:498: in function `InitializeAddon'
[string "@ArkInventory\Externals\Ace3\AceAddon\AceAddon-3.0-13.lua"]:623: in function <...rkInventory\Externals\Ace3\AceAddon\AceAddon-3.0.lua:615>`

**Comment by doadin** [comment]
Does this happen if you disable other addons?

**Comment by Jee20** [comment]
when disabling arkinventory addon, getting nor error nor indicatordynamic options in Plexus...

**Comment by doadin** [comment]
if you could send me your saved variables by attaching them here Thanks!
normaly found : 
C:\Program Files (x86)\World of Warcraft\_classic_\WTF\Account\*ACCOUNTNAMEHERE*\SavedVariables\Plexus.lua
C:\Program Files (x86)\World of Warcraft\_retail_\WTF\Account\*ACCOUNTNAMEHERE*\SavedVariables\Plexus.lua

**Comment by doadin** [comment]
Also are you getting this error on classic or retail?

**Comment by Jee20** [comment]
it's on retail.
aside note, Plexus author recently has changed the icons indicators. Now it is in camps of four overlapped icons… that’s why I had to return to indicatordynamic…

[Plexus.zip](https://github.com/doadin/PlexusIndicatorsDynamic/files/5549967/Plexus.zip)

**Comment by Jee20** [comment]
well… it seems my plexus.lua is corrupted somehow… perhaps after migration from Grid or Cyrillic characters…
Just deleted old lua and got no errors and indicatordynamic options.
Will have to readd all of the buffs again.. :/

**Comment by doadin** [comment]
It maybe an error from import from grid I see where in the plexus.lua it says gid_icon_2 which the indicator id's where renamed to pid_icon_* in the change from GridIndicatorsDynamic to PlexusIndicatorsDynamic. I think I should consider removing the import option from grid it seems to be causing more harm than good. side note Plexus author is me.
